from .base_tariff_detail_model import BaseTariffDetail
from .tnb_malakoff_tariff_detail_model import TnbMalakoffTariffDetail
from .se_tariff_detail_model import SeTariffDetail
from .saj_tariff_detail_model import SajTariffDetail
from .laku_bintulu_tariff_detail_model import LakuBintuluTariffDetail
from .kuching_tariff_detail_model import KuchingTariffDetail
from .iwk_tariff_detail_model import IwkTariffDetail
from .telecommunication_tariff_detail_model import TelecommunicationTariffDetail
